# Generated by Django 4.2.4 on 2023-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isbn',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
