# Generated by Django 4.2.4 on 2023-09-10 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
